baseURL = "http://www.dgcoc.org/"
languageCode = "en-us"
title = "Alpha Church"
theme = "alpha-church"
#themesDir = "../.."

rssLimit = 5
paginate = 4

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

enableInlineShortcodes = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  tag = "tags"
#  preacher = "preachers"
  series = "series"
  writer = "writers"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    weight = 2

  [[menu.main]]
    name = "About Us"
    parent = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Leaders"
    parent = "About"
    url = "/leaders"
    weight = 2
    
  [[menu.main]]
  	name = "COVID-19 update"
  	parent = "About"
  	url = "/covid"
  	weight = 3

# The next two things may be added back if we decide to keep the sermon audio on the site. If we need to restore them, change weight of blog back to 2.

#  [[menu.main]]
#    name = "Resources"
#    url = "#"
#    weight = 3

#  [[menu.main]]
#    name = "Sermons"
#    url = "/sermons"
#    parent = "Resources"
#    weight = 1

#  [[menu.main]]
#    name = "Preachers"
#    url = "/preachers"
#    parent = "Sermons"
#    weight = 1

#  [[menu.main]]
#    name = "Best Ever"
#    url = "#"
#    parent = "Sermons"
#    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts"
#    parent = "Resources"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4
    
  [[menu.main]]
  	name = "Members"
  	weight = 5
  
  [[menu.main]]
  	name = "Responsibilities"
  	url = "/responsibilities"
  	parent = "Members"
  	weight = 1
  	
  [[menu.main]]
  	name = "Lord's Supper Topics"
  	url = "/topics"
  	parent = "Members"
  	weight = 2
  	
  [[menu.main]]
  	name = "Lord's Supper Prep"
  	url = "/lordssupper"
  	parent = "Members"
  	weight = 3

# Paramaters for the whole site
[params]
  title = "Church of Christ in Downers Grove"
#  subtitle = "Another Church Theme"
  author = "Daniel Saunders"
  languageCode = "en" # For accessibility this needs to be set. You can find all language codes at https://www.w3schools.com/tags/ref_language_codes.asp

  bible_popups = "faithlife" #faithlife, blb
  bible_version = "ESV" #HCSB, NIV, NLT, ESV, etc.
  instant_page = true

#  customCSS = ["example.css"]

  [params.banner]
    image = "img/banner3.jpg"

  [params.style]
    googleFonts = ["Noto Serif", "Cardo", "Crimson+Text", "Merriweather", "Playfair+Display:400,700", "Roboto+Slab"]

#  [params.podcast]
#    title = "DGCOC Podcast"
#    subtitle = ""
#    summary = "Alpha-Church sermons, talks, messages—podcasted."
#    email = "test@example.com"
#    copyright = "Podcast: [CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)"
#    image = "img/podcast-cover.jpg"
#    category = "Religion & Spirituality"
#    sub_category = "Christianity"
#    iTunes = "https://podcasts.apple.com/us/podcast/downers-grove-church-of-christ/id982477742"
#    feed = ""

  [params.map]
    service = "osm" #"osm" for OpenStreetMaps, "google" for Google Maps, or "mapbox" for Mapbox, see SETUP.md
    # For Open Street Map widgets
    latitude = "41.7741972"
    longitude = "-88.0153404"
    zoom = "16"
    # If you want to use google maps you'll need an API Key from Google https://developers.google.com/maps/documentation/embed/get-api-key
    #service = "google"
    #api_key = "XXXXXXXX"
    #language = "fr" #Optional
    #region = "FR" #Optional
    
  [params.recentposts]
  	title = "Latest Posts"

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or else users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "formspree"
   # confirm_page = "/contact_thanks"
    formspree_email="dgcocit@gmail.com"


    [params.footer]
      copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)",
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
                  ]

#    [[params.links]]
#      service = "Twitter"
#      icon = "fa-twitter"
#      icon_pack = "fab"
#      link = "//twitter.com/"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/dgchurchofchrist"

    [[params.links]]
      service = "Podcast"
      icon = "fa-podcast"
      icon_pack = "fas"
      link = "/sermons/index.xml"
      
    [[params.links]]
      service = "YouTube"
      icon = "fa-youtube"
      icon_pack = "fab"
      link = "//youtube.com/channel/UC0kUKcP_9v4_WfhyDAN5DOg"

#    [[params.links]]
#      service = "Full RSS Feed"
#      icon = "fa-rss"
#      icon_pack = "fas"
#      link = "/index.xml"
